### PR TITLE
Add French (FR) language

### PR DESCRIPTION
**Pull request by jdbruxelles**

### CODE REVIEW

**Comment by yoksel** [comment]
Check it locally, page does not work

**Comment by jdbruxelles** [comment]
I can not really test it locally because running `npm start` after `npm install` triggers many errors that I don't understand.

**Comment by jdbruxelles** [comment]
HullofriendHeythereguyGIF

**Comment by jdbruxelles** [comment]
Hi @yoksel, I'm going to close this pull request in two days. 🫡

**Pull request closed without merging**
